pipeline {
    agent {
        label 'docker' // Ensure the agent label is appropriate for your Jenkins setup
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:16-alpine'
                    args '-v /root/.npm:/root/.npm' // Optional: Use args to pass additional Docker options
                }
            }
            steps {
                script {
                    echo 'Building in Docker...'
                    sh 'node --version'
                }
            }
        }
    }
}
